# -*- coding: utf-8 -*-
"""task6_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HLF6724jaoMnZtyw8Vo9h_4ezXye1O3
"""

def read_file(filename):
    lines = []
    with open(filename, 'r', encoding='utf-8') as f:
        for line in f:
            lines.append(line.rstrip('\n'))
    return lines