# -*- coding: utf-8 -*-
"""task7_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HLF6724jaoMnZtyw8Vo9h_4ezXye1O3
"""

def check_input(elem):
    return isinstance(elem, str)


def get_substring(s):
    max_sub = ""
    start = 0
    used_chars = {}

    for i, char in enumerate(s):
        if char in used_chars and used_chars[char] >= start:
            start = used_chars[char] + 1
        if i - start + 1 > len(max_sub):
            max_sub = s[start:i+1]
        used_chars[char] = i

    return max_sub


def main(lst):
    max_len = -1
    max_idx = -1
    max_str = ""

    for idx, elem in enumerate(lst):
        if check_input(elem):
            if len(elem) > max_len:
                max_len = len(elem)
                max_idx = idx
                max_str = elem

    if max_idx == -1:
        print(-1, '')
    else:
        longest_sub = get_substring(max_str)
        print(max_idx, longest_sub)